' OSLANG 0.6 - Animal inheritance example
USING OSL.I18N
CLASS Animal
    VAR Name String

    CONSTRUCTOR(Name String)
        ME.Name = Name
    END

    PUBLIC GET_NAME()
        RETURN ME.Name
    END
END

CLASS Mammal: Animal
    VAR Sound String

    CONSTRUCTOR(Name String, Sound String)
        BASE(Name)
        ME.Sound = Sound
    END

    PUBLIC GET_SOUND()
        RETURN ME.Sound
    END
END

CLASS Dog: Mammal
    CONSTRUCTOR(Name String)
        BASE(Name, "Woof")
    END

    PUBLIC GET_SOUND()
        RETURN BASE.GET_SOUND()
    END
END

FUNCTION MAIN()
    PRINT I18N.GET("animal.example")
    fifi = new Dog("Fifi")
    saida = Fifi.GET_SOUND()
    PRINT saida
END
