' OSLANG 0.51 - Fibonacci
FUNCTION FIBONACCI(QUANTITY)
    A = 0
    B = 1
    FOR I = 1 TO QUANTITY
        SHOW A + " "
        NEXT = A + B
        A = B
        B = NEXT
    END
    PRINT ""
END FUNCTION

FUNCTION MAIN()
    CLEAR
    PRINT "FIBONACCI"
    PRINT "=========="
    PRINT ""
    SHOW "How many numbers do you want? "
    INPUT Quantity
    PRINT "NICE!"
    Total = NUMBER(Quantity)
    IF Total <= 0 THEN
        PRINT "Quantity must be greater than zero."
        RETURN
    END
    FIBONACCI(Total)
END FUNCTION
